-- CreateEnum
CREATE TYPE "REASON" AS ENUM ('MEDICAL', 'INJURY', 'LEAVE', 'LATE', 'SANCTION', 'NOT_PLAYING');

-- AlterTable
ALTER TABLE "PlayerAttendance" ADD COLUMN     "reason" "REASON" NOT NULL DEFAULT E'NOT_PLAYING';
