export enum FIELD_POSITION {
    NONE = 'NONE',
    ATTACKING_MIDFIELDER = 'ATTACKING_MIDFIELDER',
    CENTER_BACK = 'CENTER_BACK',
    CENTER_FORWARD = 'CENTER_FORWARD',
    CENTER_MIDDLEFIELDER = 'CENTER_MIDDLEFIELDER',
    DEFENSIVE_MIDFIELDER = 'DEFENSIVE_MIDFIELDER',
    GOAL_KEEPER = 'GOAL_KEEPER',
    LEFT_FULLBACK = 'LEFT_FULLBACK',
    LEFT_MIDDLEFIELDER = 'LEFT_MIDDLEFIELDER',
    RIGHT_FULLBACK = 'RIGHT_FULLBACK',
    RIGHT_MIDDLEFIELDER = 'RIGHT_MIDDLEFIELDER',
    SWEEPER = 'SWEEPER',
}
