export enum FIELD_POSITION {
    NONE,
    ATTACKING_MIDFIELDER,
    CENTER_BACK,
    CENTER_FORWARD,
    CENTER_MIDDLEFIELDER,
    DEFENSIVE_MIDFIELDER,
    GOAL_KEEPER,
    LEFT_FULLBACK,
    LEFT_MIDDLEFIELDER,
    RIGHT_FULLBACK,
    RIGHT_MIDDLEFIELDER,
    SWEEPER,
}
