import { Player_Category } from '~/generated/graphql'

export const initialValues = {
    IMC: 0,
    birthday: '',
    category: Player_Category,
    createdAt: '',
    familySupport: '',
    fieldPosition: '',
    guardianEmail: '',
    guardianId: '',
    guardianIdType: '',
    guardianLastName: '',
    guardianName: '',
    guardianPhone: '',
    guardianType: '',
    height: 0,
    hobbies: '',
    id: '',
    image: '',
    lastName: '',
    name: '',
    personalQualities: '',
    physicalCapabilities: '',
    physicalQualities: '',
    placeOfBirth: '',
    playerEmail: '',
    playerId: '',
    playerIdType: '',
    playerNumber: 0,
    playerPhone: '',
    school: '',
    schoolId: '',
    sportHistory: '',
    updatedAt: '',
    weight: 0,
}
