name: Backend CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

  workflow_dispatch:

defaults:
  run:
    working-directory: ./back

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    # if: github.event_name == 'push' && github.ref == 'refs/heads/develop'

    steps:
    - uses: actions/checkout@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Run clean install
      run: npm ci
    - name: Run stage migration
      run: npx prisma migrate deploy
      env:
        DATABASE_URL: ${{secrets.DATABASE_URL}}
    - name: Run types generation
      run: npx prisma generate
      env:
        DATABASE_URL: ${{secrets.DATABASE_URL}}
    - name: build the app
      run: npm run build
      env:
        DATABASE_URL: ${{secrets.DATABASE_URL}}
        FRONT_URL: ${{secrets.FRONT_URL}}
        JWT_SECRET: ${{secrets.JWT_SECRET}}
        PORT: ${{secrets.PORT}}
        REDIS_URL: ${{secrets.REDIS_URL}}
        SESSION_SECRET: ${{secrets.SESSION_SECRET}}
    - uses: akhileshns/heroku-deploy@v3.4.6
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
        heroku_email: ${{secrets.HEROKU_EMAIL}}
        appdir: "back"
