name: Backend CI

on:
  pull_request:
    branches: [ master, develop ]

  workflow_dispatch:

defaults:
  run:
    working-directory: ./back

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        node-version: 16.x
        cache: 'npm'
    - name: Install yarn
      run: |
        curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
    - name: CI install
      run: yarn install --frozen-lockfile
    - name: build the app
      run: yarn build
    - uses: akhileshns/heroku-deploy@v3.4.6
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
        heroku_email: ${{secrets.HEROKU_EMAIL}}
        appdir: "back"
