name: Backend CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

  workflow_dispatch:

defaults:
  run:
    working-directory: ./back

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        node-version: 16.x
        cache: 'npm'
    - name: CI install
      run: npm ci
    - name: build the app
      run: npm run build
      env:
        NODE_ENV: production
        CORS_ORIGIN: ${{secrets.CORS_ORIGIN}}
        DATABASE_URL: ${{secrets.DATABASE_URL}}
        FRONT_URL: ${{secrets.FRONT_URL}}
        JWT_SECRET: ${{secrets.JWT_SECRET}}
        PORT: ${{secrets.PORT}}
        REDIS_URL: ${{secrets.REDIS_URL}}
        SESSION_SECRET: ${{secrets.SESSION_SECRET}}
    - uses: akhileshns/heroku-deploy@v3.4.6
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
        heroku_email: ${{secrets.HEROKU_EMAIL}}
        appdir: "back"
