name: Backend CI

on:
  pull_request:
    branches: [ master, develop ]

  workflow_dispatch:

defaults:
  run:
    working-directory: ./back

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        node-version: 16.x
        cache: 'npm'
    - name: DB migration
      run: npx prisma migrate dev
      env:
        DATABASE_URL: ${{secrets.DATABASE_URL}}
        SHADOW_DATABASE_URL: ${{secrets.SHADOW_DATABASE_URL}}
    - name: CI install
      run: npm ci
    - name: build the app
      run: npm run build
    - uses: akhileshns/heroku-deploy@v3.4.6
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
        heroku_email: ${{secrets.HEROKU_EMAIL}}
        appdir: "back"
