export enum FAMILY_SUPPORT {
    NONE = 'NONE',
    BOTH_GRANDFATHERS = 'BOTH_GRANDFATHERS',
    BOTH_PARENTS = 'BOTH_PARENTS',
    FATHER = 'FATHER',
    GRANDFATHER = 'GRANDFATHER',
    GRANDMOTHER = 'GRANDMOTHER',
    MOTHER = 'MOTHER',
}
