export enum PHYSICAL_CAPABILITIES {
    NONE = 'NONE',
    BALANCE = 'BALANCE',
    COORDINATION = 'COORDINATION',
    FLEXIBILITY = 'FLEXIBILITY',
    RESISTANCE = 'RESISTANCE',
    SPEED = 'SPEED',
    STRENGTH = 'STRENGTH',
}
